language: php

cache:
    directories:
        - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
      env: COVERALLS=1 PHPVERSION=5.4
      
    - php: 5.5
      env: COVERALLS=1 PHPVERSION=5.5

    - php: 5.6
      env: COVERALLS=1 PHPVERSION=5.6

    - php: hhvm
      env: COVERALLS=0 PHPVERSION=hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - mkdir -p ./build/logs
  - sh -c "if [ '$COVERALLS' = '1' ]; then ./vendor/bin/phpunit --stderr -v --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '0' ]; then ./vendor/bin/phpunit --stderr -v; fi"

after_script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php ./vendor/bin/coveralls -v; fi"

notifications:
  email:
    - florian.meyer@stinger-soft.net
